### ISSUE TITLE
Add ExpandedList to button in sidebar

### ISSUE THREAD

**Issue by MoSattler** [HandsOnLearning/the-project#109]
### Visuals

![Screenshot_2020-05-11 Morning – Habitify Web](https://user-images.githubusercontent.com/64152453/81546789-29d05100-937b-11ea-940f-16c8d3d5398e.png)

~This is blocked by #108 and cannot be started before that~

Reuse [`<ExpandedList />`](https://github.com/HandsOnLearning/the-project/tree/master/src/components/Sidebar/components/ExpandedList) for this.

**Comment by limbovski** [comment]
Closed in #188
