### ISSUE TITLE
Long email addresses make sidebar wider and don't cut off with '...'

### ISSUE THREAD

**Issue by limbovski** [HandsOnLearning/the-project#110]

**Comment by MoSattler** [comment]
@limbovski can you provide a screenshot?

**Comment by SimonNord** [comment]
![](https://cdn.discordapp.com/attachments/709336888237883424/709338158432649257/Screenshot_2020-05-11_at_10.36.22_.png)

**Comment by SimonNord** [comment]
So here is a comparision.

normal with short hardcoded email address:
<img width="436" alt="Skärmavbild 2020-05-11 kl  11 53 41" src="https://user-images.githubusercontent.com/53083229/81548855-33a78380-937e-11ea-8f92-fa9a57f712b7.png">

with a new too long email:
<img width="616" alt="Skärmavbild 2020-05-11 kl  11 54 08" src="https://user-images.githubusercontent.com/53083229/81548890-402bdc00-937e-11ea-8aa1-cfe3aa78ce19.png">

**Comment by SimonNord** [comment]
Here are some screenshots:

With a short email
<img width="366" alt="Skärmavbild 2020-05-11 kl  11 53 41" src="https://user-images.githubusercontent.com/53083229/81551383-0d83e280-9382-11ea-9da3-db470828201f.png">

With a long email
<img width="461" alt="Skärmavbild 2020-05-11 kl  11 54 08" src="https://user-images.githubusercontent.com/53083229/81551405-15438700-9382-11ea-8c1b-7bbabb868a4f.png">

**Comment by SimonNord** [comment]
Not sure which container is causing the problem
