### ISSUE TITLE
Fix UserCard Layout

### ISSUE THREAD

**Issue by MoSattler** [HandsOnLearning/the-project#154]
![Screenshot_2020-05-14 React App](https://user-images.githubusercontent.com/64152453/81942939-116e6980-95fb-11ea-8538-0aacd7f776a8.png)

The Link messed up the styles of the text. 

We want it to be like this:
![1111](https://user-images.githubusercontent.com/64152453/81943072-38c53680-95fb-11ea-93ff-b8bdc574cf00.png)

**Comment by SimonNord** [comment]
yeah I saw that before, I´m on it
