### ISSUE TITLE
Wrap ExpandedList inside a Spacer

### ISSUE THREAD

**Issue by limbovski** [HandsOnLearning/the-project#176]
@limbovski once this is merged, you should be able to wrap it inside a `Spacer` like this
```jsx
<Spacer left={x} right={y}>
  {/*content*/}
</Spacer>
```

_Originally posted by @MoSattler in https://github.com/HandsOnLearning/the-project/pull/167#issuecomment-629679528_

**Comment by limbovski** [comment]
Had a look at this and I'm inclined to leave it as is.

The ExpandedList is positioned: absolute. So it ignores the padding from Spacer.

We would have to make this really ugly to use Spacer I think. Maybe you could have a look @MoSattler ?

**Comment by MoSattler** [comment]
leave it as it is for now, that's fine
