### ISSUE TITLE
Rename Routes to Route

### ISSUE THREAD

**Issue by MoSattler** [HandsOnLearning/the-project#202]
Enums should have singular names.
Code [here](https://github.com/HandsOnLearning/the-project/blob/master/src/variables.ts#L13).

**Comment by limbovski** [comment]
This causes a duplicate identifier error with Route from react-router-dom.

Is there a way around that? Might be confusing?

**Comment by MoSattler** [comment]
Good point. We could rename this to `PageRoute` or something like that. Your call!

**Comment by limbovski** [comment]
Closed by #204
