### ISSUE TITLE
Add UserCard

### ISSUE THREAD

**Issue by MoSattler** [HandsOnLearning/the-project#44]
#### Collapsed (click on image to see all details):
![Screenshot_2020-05-03 All Habits – Habitify Web](https://user-images.githubusercontent.com/64152453/80912940-efdec980-8d40-11ea-9bcc-a194bb7e79de.png)

#### Expanded (click on image to see all details):
![Screenshot_2020-05-03 All Habits – Habitify Web(1)](https://user-images.githubusercontent.com/64152453/80913085-14877100-8d42-11ea-8d21-91a19d2d628b.png)
Please note that we want to skip "Free Member", since this is not a paid app :)

### notes: 
- `border-radius` of both boxes is 3px
- the boxes have a space between content and border of 15px
- `background-color` of collapsed box is [White](https://github.com/HandsOnLearning/the-project/blob/master/src/variables.ts#L4)
- background color of expanded box is [LimedSpruce](https://github.com/HandsOnLearning/the-project/blob/master/src/variables.ts#L3)
- [Get avatar](https://publicdomainvectors.org/photos/generic-avatar.png)
- [Get icon on the right](https://primer.style/octicons/chevron-down) (download as svg)

#### Fonts
| Element            | Value in Example         | font-size | line-height | font-weight | color              |
|--------------------|--------------------------|-----------|-------------|-------------|--------------------|
| Name               | Guest                    | 15px      | 18px        | 600         | White              |
| Email              | teststuff@localhost.c... | 13px      | 18px        | 500         | `hsla(0,0%,100%,.5)` |
| Expanded List Text | Profile & Settings       | 15px      | 18px        | 500         | [CodGray](https://github.com/HandsOnLearning/the-project/blob/master/src/variables.ts#L5)            |

#### Challenges:
- adding styling
- handling state (collapsed vs expanded)
- props (user info will be passed as props)
- icons (add svg icon)
- images (add avatar)

## Getting started
Since this is one of the first tasks, I want to the instructions on how to get started. Since this is an isolated component you will develop, you will develop it in storybook.

1. Go to master branch, and pull the latest code
2. Make a new branch `git branch -b [branchname]`
3. Run `npm install`
4. Run `npm run storybook` 
5. Go to http://localhost:9009/?path=/story/usercard--user-card-story
6. Make some changes in [/src/components/Sidebar/components/UserCard/UserCard](https://github.com/HandsOnLearning/the-project/blob/master/src/components/Sidebar/components/UserCard/UserCard.tsx)
7. See how it changes in storybook
8. Start coding :)

**Comment by SimonNord** [comment]
@MoSattler Get avatar link does not work

**Comment by MoSattler** [comment]
weird, it works for me. in Any case, I have it attached:
![generic-avatar](https://user-images.githubusercontent.com/64152453/80915320-e742bf00-8d51-11ea-8101-7e8c60e15168.png)

**Comment by SimonNord** [comment]
Cool thanks =) it was a permission issue

Just a note, here is the error msg:

"What happened?
The owner of this website (publicdomainvectors.org) does not allow hotlinking to that resource (/photos/generic-avatar.png)."

**Comment by MoSattler** [comment]
yeah, probably because it came from a link. All good now?

**Comment by SimonNord** [comment]
yeah, getting the image from your comment =)
