### ISSUE TITLE
Add tests for user card

### ISSUE THREAD

**Issue by MoSattler** [HandsOnLearning/the-project#68]
I added some basic tests for UserCard, you can find them [here](https://github.com/HandsOnLearning/the-project/blob/master/src/components/Sidebar/components/UserCard/UserCard.test.js).

I left two tests as todo, and I want you to complete them. Take inspiration from the two tests that are already written :). 

To run tests execute
```bash
$ npm test
```

**Comment by SimonNord** [comment]
Issue closed in #78
