### ISSUE TITLE
Make `FormattedText`'s weight configurable via prop 

### ISSUE THREAD

**Issue by MoSattler** [HandsOnLearning/the-project#95]
We want to be able to have a FormattedText component that is configurable. 
Let's start with the weight. 
The goal is to be able to use it like this
```javascript
<FormattedText weight="bold" >
  I am bold text
</FormattedText>
```
Right now the `font-weight` is always `500`. But with `weight` we want to be able to change these values: 
- `regular` -> sets  `font-weight` to `400`
- `medium` -> sets  `font-weight` to `500`
- `bold` -> sets  `font-weight` to `600`

`weight` should be an optional prop, and have a default value of `medium`. 

### Notes:
This task requires work on
- typescript (adding `weight` to the [props type](https://github.com/HandsOnLearning/the-project/blob/master/src/components/FormattedText/FormattedText.tsx#L5-L8))
- props
- styling (having props [map to the font-weight values](https://github.com/HandsOnLearning/the-project/blob/master/src/components/FormattedText/FormattedText.tsx#L12)).

**Comment by MoSattler** [comment]
One thing that might help:
Change the [FormattedText story](https://github.com/HandsOnLearning/the-project/blob/master/src/components/FormattedText/FormattedText.stories.tsx) to this
```javascript
export const FormattedTextStory = () => (
  <div>
    <FormattedText weight="regular">I should be black</FormattedText>
    <Seperator />
    <FormattedText weight="medium" color={Color.DodgerBlue}>I should be blue</FormattedText>
    <Seperator />
    <FormattedText weight="bold" color={Color.White}>I should be white</FormattedText>
  </div>
);
```
so you can see if the thing you are doing is actually working!

**Comment by limbovski** [comment]
Do you want me to use CSS Keyword Values to set the actual style i.e. the strings; regular, medium bold or should I be setting this with with the numeric keyword value i.e. 400 / 500 / 600 (bold is default 700)?

**Comment by SimonNord** [comment]
@limbovski Checked out this branch, mby its already merged, but noticed that there was one typo in the return

```
return (
    <span
      css={`
        font-size: 15px;
        fontweight: ${fontWeights[props.weight]};
        color: ${props.color};
      `}
    >
      {props.children}
    </span>
  );
```

If you change `fontWeight` to `font-weight` everything else is working.
